### ISSUE TITLE
Books "Card" embed logic breaks the page

### ISSUE THREAD

**Issue by luke-hill** [cucumber/docs#864] opened 2023-03-22 10:37 UTC
### 👓 What did you see?

`/docs/professional/books/` is broken badly. The `card` embed logic seems to be causing this.

### ✅ What did you expect to see?

Page rendering nicely

### 📦 Which tool/library version are you using?

N/A

### 🔬 How could we reproduce it?

Visit https://cucumber.io/docs/professional/books/

### 📚 Any additional context?

N/A

**Comment by mpkorstanje** [comment] 2023-03-22 12:03
Probably a duplicate of https://gitlab.com/dna-platform/api/libraries/api-micronaut-commons/-/merge_requests/57

**Closed as completed by mpkorstanje** 2023-03-22 12:03 UTC
Labels: :bug: bug

**Comment by mpkorstanje** [comment] 2023-03-22 12:11
Probably a duplicate of https://github.com/cucumber/docs/issues/817
